default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch('DEVELOPMENT_DATABASE_URL') { '' } %>

test:
  <<: *default
  url: <%= ENV.fetch('TEST_DATABASE_URL') { '' } %>

production:
  url: <%= ENV.fetch('DATABASE_URL') { '' } %>
